name: Create Release

on:
  workflow_dispatch:

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write
      actions: write
      issues: write
      pull-requests: write

    steps:
      - name: Checkout the repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Ensure that all tags are fetched

      - name: Cancel if commit already exists on remote
        run: |
          git fetch origin main
          if git branch -r --contains $GITHUB_SHA | grep origin/main; then
            echo "Commit já existe na main remota. Cancelando workflow."
            exit 0
          fi

      - name: Set up Bun
        if: success() && !contains(steps.cancel.outputs.skipped, 'true')
        uses: oven-sh/setup-bun@v2

      - name: Install dependencies
        run: bun install

      - name: Run Semantic Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: bun semantic-release